# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-29 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('avatar', models.CharField(default='http://i.imgur.com/eoeGSNb.gif', max_length=1024)),
                ('description', models.CharField(default='No description available.', max_length=2028)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1024)),
                ('author', models.CharField(default='Anon', max_length=30)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title_text', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('body_text', models.CharField(max_length=2048)),
                ('img', models.CharField(max_length=1024)),
                ('log_text', models.CharField(default='No logs available.', max_length=9000)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Posts'),
        ),
    ]
