# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='github',
        ),
        migrations.AddField(
            model_name='name',
            name='github',
            field=models.CharField(default='Your Github', max_length=24),
        ),
        migrations.AddField(
            model_name='name',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
