# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160229_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.CharField(default='https://www.codeleakers.com/images/styles/TheBeaconDark/style/logo.png', max_length=1024),
        ),
    ]
