# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160223_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='picture',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/7/7e/Patrick_Star.png', max_length=1024),
        ),
    ]
