# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_name_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='github',
        ),
        migrations.AddField(
            model_name='name',
            name='reddit',
            field=models.CharField(default='Your Reddit uname', max_length=24),
        ),
    ]
