# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160224_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=72)),
                ('author', models.CharField(default='MarlosTiltingMe', max_length=16)),
                ('body_text', models.CharField(max_length=2048)),
            ],
        ),
    ]
