# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/7/7e/Patrick_Star.png', max_length=1024),
        ),
    ]
