# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_posts_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.CharField(max_length=1024),
        ),
    ]
