# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160225_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1024)),
                ('parent_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Posts')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
