# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160226_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='Anon', max_length=30),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='MarlosTiltingMe', max_length=30),
        ),
    ]
