# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20160226_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
