# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-02-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_name',
            field=models.CharField(default='Noname', max_length=30),
        ),
    ]
